/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AtivosRouteImport } from './routes/ativos'
import { Route as CarrinhoRouteImport } from './routes/carrinho'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ContaRouteImport } from './routes/conta'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as KitsRouteImport } from './routes/kits'
import { Route as LojaRouteImport } from './routes/loja'
import { Route as RastreioRouteImport } from './routes/rastreio'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAuditoriaRouteImport } from './routes/admin.auditoria'
import { Route as AdminBannersRouteImport } from './routes/admin.banners'
import { Route as AdminConfiguracoesRouteImport } from './routes/admin.configuracoes'
import { Route as AdminCuponsRouteImport } from './routes/admin.cupons'
import { Route as AdminEstoqueRouteImport } from './routes/admin.estoque'
import { Route as AdminPedidosRouteImport } from './routes/admin.pedidos'
import { Route as AdminProdutosRouteImport } from './routes/admin.produtos'
import { Route as PedidoIdRouteImport } from './routes/pedido.$id'
import { Route as PoliticasSlugRouteImport } from './routes/politicas.$slug'
import { Route as ProdutoSlugRouteImport } from './routes/produto.$slug'
import { Route as ApiPublicWebhooksMercadopagoRouteImport } from './routes/api/public/webhooks/mercadopago'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AtivosRoute = AtivosRouteImport.update({
  id: '/ativos',
  path: '/ativos',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrinhoRoute = CarrinhoRouteImport.update({
  id: '/carrinho',
  path: '/carrinho',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ContaRoute = ContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const KitsRoute = KitsRouteImport.update({
  id: '/kits',
  path: '/kits',
  getParentRoute: () => rootRouteImport,
} as any)
const LojaRoute = LojaRouteImport.update({
  id: '/loja',
  path: '/loja',
  getParentRoute: () => rootRouteImport,
} as any)
const RastreioRoute = RastreioRouteImport.update({
  id: '/rastreio',
  path: '/rastreio',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditoriaRoute = AdminAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBannersRoute = AdminBannersRouteImport.update({
  id: '/banners',
  path: '/banners',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfiguracoesRoute = AdminConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCuponsRoute = AdminCuponsRouteImport.update({
  id: '/cupons',
  path: '/cupons',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEstoqueRoute = AdminEstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPedidosRoute = AdminPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProdutosRoute = AdminProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => AdminRoute,
} as any)
const PedidoIdRoute = PedidoIdRouteImport.update({
  id: '/pedido/$id',
  path: '/pedido/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticasSlugRoute = PoliticasSlugRouteImport.update({
  id: '/politicas/$slug',
  path: '/politicas/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutoSlugRoute = ProdutoSlugRouteImport.update({
  id: '/produto/$slug',
  path: '/produto/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksMercadopagoRoute =
  ApiPublicWebhooksMercadopagoRouteImport.update({
    id: '/api/public/webhooks/mercadopago',
    path: '/api/public/webhooks/mercadopago',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/ativos': typeof AtivosRoute
  '/carrinho': typeof CarrinhoRoute
  '/checkout': typeof CheckoutRoute
  '/conta': typeof ContaRoute
  '/contato': typeof ContatoRoute
  '/faq': typeof FaqRoute
  '/kits': typeof KitsRoute
  '/loja': typeof LojaRoute
  '/rastreio': typeof RastreioRoute
  '/sobre': typeof SobreRoute
  '/admin/auditoria': typeof AdminAuditoriaRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/cupons': typeof AdminCuponsRoute
  '/admin/estoque': typeof AdminEstoqueRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/produtos': typeof AdminProdutosRoute
  '/pedido/$id': typeof PedidoIdRoute
  '/politicas/$slug': typeof PoliticasSlugRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/webhooks/mercadopago': typeof ApiPublicWebhooksMercadopagoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ativos': typeof AtivosRoute
  '/carrinho': typeof CarrinhoRoute
  '/checkout': typeof CheckoutRoute
  '/conta': typeof ContaRoute
  '/contato': typeof ContatoRoute
  '/faq': typeof FaqRoute
  '/kits': typeof KitsRoute
  '/loja': typeof LojaRoute
  '/rastreio': typeof RastreioRoute
  '/sobre': typeof SobreRoute
  '/admin/auditoria': typeof AdminAuditoriaRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/cupons': typeof AdminCuponsRoute
  '/admin/estoque': typeof AdminEstoqueRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/produtos': typeof AdminProdutosRoute
  '/pedido/$id': typeof PedidoIdRoute
  '/politicas/$slug': typeof PoliticasSlugRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/admin': typeof AdminIndexRoute
  '/api/public/webhooks/mercadopago': typeof ApiPublicWebhooksMercadopagoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/ativos': typeof AtivosRoute
  '/carrinho': typeof CarrinhoRoute
  '/checkout': typeof CheckoutRoute
  '/conta': typeof ContaRoute
  '/contato': typeof ContatoRoute
  '/faq': typeof FaqRoute
  '/kits': typeof KitsRoute
  '/loja': typeof LojaRoute
  '/rastreio': typeof RastreioRoute
  '/sobre': typeof SobreRoute
  '/admin/auditoria': typeof AdminAuditoriaRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/cupons': typeof AdminCuponsRoute
  '/admin/estoque': typeof AdminEstoqueRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/produtos': typeof AdminProdutosRoute
  '/pedido/$id': typeof PedidoIdRoute
  '/politicas/$slug': typeof PoliticasSlugRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/webhooks/mercadopago': typeof ApiPublicWebhooksMercadopagoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/ativos'
    | '/carrinho'
    | '/checkout'
    | '/conta'
    | '/contato'
    | '/faq'
    | '/kits'
    | '/loja'
    | '/rastreio'
    | '/sobre'
    | '/admin/auditoria'
    | '/admin/banners'
    | '/admin/configuracoes'
    | '/admin/cupons'
    | '/admin/estoque'
    | '/admin/pedidos'
    | '/admin/produtos'
    | '/pedido/$id'
    | '/politicas/$slug'
    | '/produto/$slug'
    | '/admin/'
    | '/api/public/webhooks/mercadopago'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ativos'
    | '/carrinho'
    | '/checkout'
    | '/conta'
    | '/contato'
    | '/faq'
    | '/kits'
    | '/loja'
    | '/rastreio'
    | '/sobre'
    | '/admin/auditoria'
    | '/admin/banners'
    | '/admin/configuracoes'
    | '/admin/cupons'
    | '/admin/estoque'
    | '/admin/pedidos'
    | '/admin/produtos'
    | '/pedido/$id'
    | '/politicas/$slug'
    | '/produto/$slug'
    | '/admin'
    | '/api/public/webhooks/mercadopago'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/ativos'
    | '/carrinho'
    | '/checkout'
    | '/conta'
    | '/contato'
    | '/faq'
    | '/kits'
    | '/loja'
    | '/rastreio'
    | '/sobre'
    | '/admin/auditoria'
    | '/admin/banners'
    | '/admin/configuracoes'
    | '/admin/cupons'
    | '/admin/estoque'
    | '/admin/pedidos'
    | '/admin/produtos'
    | '/pedido/$id'
    | '/politicas/$slug'
    | '/produto/$slug'
    | '/admin/'
    | '/api/public/webhooks/mercadopago'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AtivosRoute: typeof AtivosRoute
  CarrinhoRoute: typeof CarrinhoRoute
  CheckoutRoute: typeof CheckoutRoute
  ContaRoute: typeof ContaRoute
  ContatoRoute: typeof ContatoRoute
  FaqRoute: typeof FaqRoute
  KitsRoute: typeof KitsRoute
  LojaRoute: typeof LojaRoute
  RastreioRoute: typeof RastreioRoute
  SobreRoute: typeof SobreRoute
  PedidoIdRoute: typeof PedidoIdRoute
  PoliticasSlugRoute: typeof PoliticasSlugRoute
  ProdutoSlugRoute: typeof ProdutoSlugRoute
  ApiPublicWebhooksMercadopagoRoute: typeof ApiPublicWebhooksMercadopagoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ativos': {
      id: '/ativos'
      path: '/ativos'
      fullPath: '/ativos'
      preLoaderRoute: typeof AtivosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrinho': {
      id: '/carrinho'
      path: '/carrinho'
      fullPath: '/carrinho'
      preLoaderRoute: typeof CarrinhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conta': {
      id: '/conta'
      path: '/conta'
      fullPath: '/conta'
      preLoaderRoute: typeof ContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kits': {
      id: '/kits'
      path: '/kits'
      fullPath: '/kits'
      preLoaderRoute: typeof KitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loja': {
      id: '/loja'
      path: '/loja'
      fullPath: '/loja'
      preLoaderRoute: typeof LojaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rastreio': {
      id: '/rastreio'
      path: '/rastreio'
      fullPath: '/rastreio'
      preLoaderRoute: typeof RastreioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/auditoria': {
      id: '/admin/auditoria'
      path: '/auditoria'
      fullPath: '/admin/auditoria'
      preLoaderRoute: typeof AdminAuditoriaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/banners': {
      id: '/admin/banners'
      path: '/banners'
      fullPath: '/admin/banners'
      preLoaderRoute: typeof AdminBannersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/configuracoes': {
      id: '/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AdminConfiguracoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cupons': {
      id: '/admin/cupons'
      path: '/cupons'
      fullPath: '/admin/cupons'
      preLoaderRoute: typeof AdminCuponsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/estoque': {
      id: '/admin/estoque'
      path: '/estoque'
      fullPath: '/admin/estoque'
      preLoaderRoute: typeof AdminEstoqueRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pedidos': {
      id: '/admin/pedidos'
      path: '/pedidos'
      fullPath: '/admin/pedidos'
      preLoaderRoute: typeof AdminPedidosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/produtos': {
      id: '/admin/produtos'
      path: '/produtos'
      fullPath: '/admin/produtos'
      preLoaderRoute: typeof AdminProdutosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/pedido/$id': {
      id: '/pedido/$id'
      path: '/pedido/$id'
      fullPath: '/pedido/$id'
      preLoaderRoute: typeof PedidoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politicas/$slug': {
      id: '/politicas/$slug'
      path: '/politicas/$slug'
      fullPath: '/politicas/$slug'
      preLoaderRoute: typeof PoliticasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produto/$slug': {
      id: '/produto/$slug'
      path: '/produto/$slug'
      fullPath: '/produto/$slug'
      preLoaderRoute: typeof ProdutoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/mercadopago': {
      id: '/api/public/webhooks/mercadopago'
      path: '/api/public/webhooks/mercadopago'
      fullPath: '/api/public/webhooks/mercadopago'
      preLoaderRoute: typeof ApiPublicWebhooksMercadopagoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAuditoriaRoute: typeof AdminAuditoriaRoute
  AdminBannersRoute: typeof AdminBannersRoute
  AdminConfiguracoesRoute: typeof AdminConfiguracoesRoute
  AdminCuponsRoute: typeof AdminCuponsRoute
  AdminEstoqueRoute: typeof AdminEstoqueRoute
  AdminPedidosRoute: typeof AdminPedidosRoute
  AdminProdutosRoute: typeof AdminProdutosRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditoriaRoute: AdminAuditoriaRoute,
  AdminBannersRoute: AdminBannersRoute,
  AdminConfiguracoesRoute: AdminConfiguracoesRoute,
  AdminCuponsRoute: AdminCuponsRoute,
  AdminEstoqueRoute: AdminEstoqueRoute,
  AdminPedidosRoute: AdminPedidosRoute,
  AdminProdutosRoute: AdminProdutosRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AtivosRoute: AtivosRoute,
  CarrinhoRoute: CarrinhoRoute,
  CheckoutRoute: CheckoutRoute,
  ContaRoute: ContaRoute,
  ContatoRoute: ContatoRoute,
  FaqRoute: FaqRoute,
  KitsRoute: KitsRoute,
  LojaRoute: LojaRoute,
  RastreioRoute: RastreioRoute,
  SobreRoute: SobreRoute,
  PedidoIdRoute: PedidoIdRoute,
  PoliticasSlugRoute: PoliticasSlugRoute,
  ProdutoSlugRoute: ProdutoSlugRoute,
  ApiPublicWebhooksMercadopagoRoute: ApiPublicWebhooksMercadopagoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
