/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AtivosRouteImport } from './routes/ativos'
import { Route as CarrinhoRouteImport } from './routes/carrinho'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as KitsRouteImport } from './routes/kits'
import { Route as LojaRouteImport } from './routes/loja'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as PedidoIdRouteImport } from './routes/pedido.$id'
import { Route as PoliticasSlugRouteImport } from './routes/politicas.$slug'
import { Route as ProdutoSlugRouteImport } from './routes/produto.$slug'
import { Route as ApiPublicWebhooksMercadopagoRouteImport } from './routes/api/public/webhooks/mercadopago'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AtivosRoute = AtivosRouteImport.update({
  id: '/ativos',
  path: '/ativos',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrinhoRoute = CarrinhoRouteImport.update({
  id: '/carrinho',
  path: '/carrinho',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const KitsRoute = KitsRouteImport.update({
  id: '/kits',
  path: '/kits',
  getParentRoute: () => rootRouteImport,
} as any)
const LojaRoute = LojaRouteImport.update({
  id: '/loja',
  path: '/loja',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidoIdRoute = PedidoIdRouteImport.update({
  id: '/pedido/$id',
  path: '/pedido/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticasSlugRoute = PoliticasSlugRouteImport.update({
  id: '/politicas/$slug',
  path: '/politicas/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutoSlugRoute = ProdutoSlugRouteImport.update({
  id: '/produto/$slug',
  path: '/produto/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksMercadopagoRoute =
  ApiPublicWebhooksMercadopagoRouteImport.update({
    id: '/api/public/webhooks/mercadopago',
    path: '/api/public/webhooks/mercadopago',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ativos': typeof AtivosRoute
  '/carrinho': typeof CarrinhoRoute
  '/checkout': typeof CheckoutRoute
  '/contato': typeof ContatoRoute
  '/faq': typeof FaqRoute
  '/kits': typeof KitsRoute
  '/loja': typeof LojaRoute
  '/sobre': typeof SobreRoute
  '/pedido/$id': typeof PedidoIdRoute
  '/politicas/$slug': typeof PoliticasSlugRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/api/public/webhooks/mercadopago': typeof ApiPublicWebhooksMercadopagoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ativos': typeof AtivosRoute
  '/carrinho': typeof CarrinhoRoute
  '/checkout': typeof CheckoutRoute
  '/contato': typeof ContatoRoute
  '/faq': typeof FaqRoute
  '/kits': typeof KitsRoute
  '/loja': typeof LojaRoute
  '/sobre': typeof SobreRoute
  '/pedido/$id': typeof PedidoIdRoute
  '/politicas/$slug': typeof PoliticasSlugRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/api/public/webhooks/mercadopago': typeof ApiPublicWebhooksMercadopagoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ativos': typeof AtivosRoute
  '/carrinho': typeof CarrinhoRoute
  '/checkout': typeof CheckoutRoute
  '/contato': typeof ContatoRoute
  '/faq': typeof FaqRoute
  '/kits': typeof KitsRoute
  '/loja': typeof LojaRoute
  '/sobre': typeof SobreRoute
  '/pedido/$id': typeof PedidoIdRoute
  '/politicas/$slug': typeof PoliticasSlugRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/api/public/webhooks/mercadopago': typeof ApiPublicWebhooksMercadopagoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ativos'
    | '/carrinho'
    | '/checkout'
    | '/contato'
    | '/faq'
    | '/kits'
    | '/loja'
    | '/sobre'
    | '/pedido/$id'
    | '/politicas/$slug'
    | '/produto/$slug'
    | '/api/public/webhooks/mercadopago'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ativos'
    | '/carrinho'
    | '/checkout'
    | '/contato'
    | '/faq'
    | '/kits'
    | '/loja'
    | '/sobre'
    | '/pedido/$id'
    | '/politicas/$slug'
    | '/produto/$slug'
    | '/api/public/webhooks/mercadopago'
  id:
    | '__root__'
    | '/'
    | '/ativos'
    | '/carrinho'
    | '/checkout'
    | '/contato'
    | '/faq'
    | '/kits'
    | '/loja'
    | '/sobre'
    | '/pedido/$id'
    | '/politicas/$slug'
    | '/produto/$slug'
    | '/api/public/webhooks/mercadopago'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtivosRoute: typeof AtivosRoute
  CarrinhoRoute: typeof CarrinhoRoute
  CheckoutRoute: typeof CheckoutRoute
  ContatoRoute: typeof ContatoRoute
  FaqRoute: typeof FaqRoute
  KitsRoute: typeof KitsRoute
  LojaRoute: typeof LojaRoute
  SobreRoute: typeof SobreRoute
  PedidoIdRoute: typeof PedidoIdRoute
  PoliticasSlugRoute: typeof PoliticasSlugRoute
  ProdutoSlugRoute: typeof ProdutoSlugRoute
  ApiPublicWebhooksMercadopagoRoute: typeof ApiPublicWebhooksMercadopagoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ativos': {
      id: '/ativos'
      path: '/ativos'
      fullPath: '/ativos'
      preLoaderRoute: typeof AtivosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrinho': {
      id: '/carrinho'
      path: '/carrinho'
      fullPath: '/carrinho'
      preLoaderRoute: typeof CarrinhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kits': {
      id: '/kits'
      path: '/kits'
      fullPath: '/kits'
      preLoaderRoute: typeof KitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loja': {
      id: '/loja'
      path: '/loja'
      fullPath: '/loja'
      preLoaderRoute: typeof LojaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedido/$id': {
      id: '/pedido/$id'
      path: '/pedido/$id'
      fullPath: '/pedido/$id'
      preLoaderRoute: typeof PedidoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politicas/$slug': {
      id: '/politicas/$slug'
      path: '/politicas/$slug'
      fullPath: '/politicas/$slug'
      preLoaderRoute: typeof PoliticasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produto/$slug': {
      id: '/produto/$slug'
      path: '/produto/$slug'
      fullPath: '/produto/$slug'
      preLoaderRoute: typeof ProdutoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/mercadopago': {
      id: '/api/public/webhooks/mercadopago'
      path: '/api/public/webhooks/mercadopago'
      fullPath: '/api/public/webhooks/mercadopago'
      preLoaderRoute: typeof ApiPublicWebhooksMercadopagoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtivosRoute: AtivosRoute,
  CarrinhoRoute: CarrinhoRoute,
  CheckoutRoute: CheckoutRoute,
  ContatoRoute: ContatoRoute,
  FaqRoute: FaqRoute,
  KitsRoute: KitsRoute,
  LojaRoute: LojaRoute,
  SobreRoute: SobreRoute,
  PedidoIdRoute: PedidoIdRoute,
  PoliticasSlugRoute: PoliticasSlugRoute,
  ProdutoSlugRoute: ProdutoSlugRoute,
  ApiPublicWebhooksMercadopagoRoute: ApiPublicWebhooksMercadopagoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
